version: '3.4'

services:  
  merchant-api:
    container_name: "merchant-api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - GRPC_PORT=81
      - PORT=80
    expose:
      - "80"
    networks:
      - joker-network        
      
  campaign-api:
    container_name: "campaign-api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - GRPC_PORT=81
      - PORT=80
    expose:
      - "80"
    networks:
      - joker-network      
        
  management-api:
    container_name: "management-api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - GRPC_PORT=81
      - PORT=80
    expose:
      - "80"
    networks:
      - joker-network      
        
  location-api:
    container_name: "location-api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - GRPC_PORT=81
      - PORT=80
    expose:
      - "80" 
    networks:
      - joker-network      
        
  search-api:
    container_name: "search-api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - GRPC_PORT=81
      - PORT=80
    expose:
      - "80"
    networks:
      - joker-network      

  favorite-api:
    container_name: "favorite-api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - GRPC_PORT=81
      - PORT=80
    expose:
      - "80"
    networks:
      - joker-network

  identity-api:
    container_name: "identity-api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - GRPC_PORT=81
      - PORT=80      
    ports:
      - "5008:80"
    networks:
      - joker-network
      
  subscription-api:
    container_name: "subscription-api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - GRPC_PORT=81
      - PORT=80
    expose:
      - "80"
    networks:
      - joker-network      
        
  aggregator-api:
    container_name: "aggregator-api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - GRPC_PORT=81
      - PORT=80
    expose:
      - "80"
    networks:
      - joker-network
      
  aggregator-storefront-api:
    container_name: "aggregator-storefront-api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - GRPC_PORT=81
      - PORT=80
    expose:
      - "80"
    networks:
      - joker-network      
        
  gateway-web-api:
    container_name: "gateway-web-api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5300:80"
    networks:
      - joker-network        

  gateway-backoffice-api:
    container_name: "gateway-backoffice-api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5400:80"
    networks:
      - joker-network
      
  joker-webapp:
    container_name: "joker-webapp"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - GatewayUrl=http://gateway-web-api
    ports:
      - "5030:80"
    networks:
      - joker-network

  joker-backoffice:
    container_name: "joker-backoffice"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - GatewayUrl=http://gateway-backoffice-api
    ports:
      - "5040:80"
    networks:
      - joker-network

networks:
  joker-network:
    external: true        