version: '3.4'
services:
  campaign-api:
    image: joker/campaignapi
    build:
      context: .
      dockerfile: src/Services/Campaign/Campaign.Api/Dockerfile

  location-api:
    image: joker/locationapi
    build:
      context: .
      dockerfile: src/Services/Location/Location.Api/Dockerfile
          
  management-api:
    image: joker/managementapi
    build:
      context: .
      dockerfile: src/Services/Management/Management.Api/Dockerfile
      
  merchant-api:
    image: joker/merchantapi
    build:
      context: .
      dockerfile: src/Services/Merchant/Merchant.Api/Dockerfile
      
  favorite-api:
    image: joker/favoriteapi
    build:
      context: .
      dockerfile: src/Services/Favorite/Favorite.Api/Dockerfile
        
  search-api:
    image: joker/searchapi
    build:
      context: .
      dockerfile: src/Services/Search/Search.Api/Dockerfile
  
  identity-api:
    image: joker/identityapi
    build:
      context: .
      dockerfile: src/Services/Identity/Joker.Identity/Dockerfile
  
  subscription-api:
    image: joker/subscriptionapi
    build:
      context: .
      dockerfile: src/Services/Subscription/Subscription.Api/Dockerfile
   
  aggregator-api:
    image: joker/aggregatorapi
    build:
      context: .
      dockerfile: src/Aggregators/Aggregator.Api/Dockerfile
    depends_on:
      - identity-api
      - search-api
      - merchant-api
      - management-api
      - subscription-api
      - location-api
      - campaign-api
  
  gateway-web-api:
    image: joker/gatewaywebapi
    build:
      context: .
      dockerfile: src/Gateways/Gateway.Web.Api/Dockerfile
    depends_on:
      - aggregator-api      
        
  joker-webapp:
    image: joker/jokerwebapp
    build:
      context: .
      dockerfile: src/WebApplications/Joker.WebApp/Dockerfile              
    depends_on:
      - gateway-web-api
