version: '3.4'

services:
  consul:
    image: consul:latest
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    container_name: consul
    networks:
      - joker-network
    ports:
      - "8500:8500"              
  seq:
    container_name: "seq"
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    volumes:
      - ./data/volumes/seq:/data  
    networks:
      - joker-network      
        
  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - joker-network      
        
  postgres:
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - ./data/volumes/postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - joker-network
    
  nosqldata:
    container_name: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - ./data/volumes/mongo:/data/db
    networks:
      - joker-network 
      
  couchbase:
     image: couchbase
     container_name: "couchbase"
     ports:
       - "8091:8091"
       - "8093:8093"
       - "11210:11210"
     networks:
       - joker-network
         
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - joker-network
        
  merchant-api:
    container_name: "merchant-api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - GRPC_PORT=81
      - PORT=80
    ports:
      - "5000:80"
    networks:
      - joker-network        
      
  campaign-api:
    container_name: "campaign-api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - GRPC_PORT=81
      - PORT=80
    ports:
      - "5001:80"
    networks:
      - joker-network      
        
  management-api:
    container_name: "management-api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - GRPC_PORT=81
      - PORT=80
    ports:
      - "5002:80"
    networks:
      - joker-network      
        
  location-api:
    container_name: "location-api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - GRPC_PORT=81
      - PORT=80
    ports:
      - "5003:80"   
    networks:
      - joker-network      
        
  search-api:
    container_name: "search-api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - GRPC_PORT=81
      - PORT=80
    ports:
      - "5004:80"
    networks:
      - joker-network      

  favorite-api:
    container_name: "favorite-api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - GRPC_PORT=81
      - PORT=80
    ports:
      - "5005:80"
    networks:
      - joker-network


  identity-api:
    container_name: "identity-api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - GRPC_PORT=81
      - PORT=80      
    ports:
      - "5008:80"
    networks:
      - joker-network
      
  subscription-api:
    container_name: "subscription-api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - GRPC_PORT=81
      - PORT=80
    ports:
      - "5007:80"
    networks:
      - joker-network      
        
  aggregator-api:
    container_name: "aggregator-api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - GRPC_PORT=81
      - PORT=80
    ports:
      - "5006:80"
    networks:
      - joker-network
        
  gateway-web-api:
    container_name: "gateway-web-api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5009:80"
    networks:
      - joker-network        

  joker-webapp:
    container_name: "joker-webapp"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - GatewayUrl=http://gateway-web-api
    ports:
      - "5030:80"
    networks:
      - joker-network

networks:
  joker-network:
    external: true        