version: '3.4'

services:
  consul:
    image: consul
    
  nosqldata:
    image: mongo
    
  postgres:
    image: postgres
    
  seq:
    image: datalust/seq:latest

  rabbitmq:
    image: rabbitmq:3-management-alpine
    
  campaign.api:
    image: ${DOCKER_REGISTRY-}campaignapi
    build:
      context: .
      dockerfile: src/Services/Campaign/Campaign.Api/Dockerfile
    depends_on:
      - nosqldata
      - seq
      - rabbitmq     
      - consul

  location.api:
    image: ${DOCKER_REGISTRY-}locationapi
    build:
      context: .
      dockerfile: src/Services/Location/Location.Api/Dockerfile
    depends_on:
      - postgres
      - seq
      - rabbitmq
      - consul
          
  management.api:
    image: ${DOCKER_REGISTRY-}managementapi
    build:
      context: .
      dockerfile: src/Services/Management/Management.Api/Dockerfile
    depends_on:
      - postgres
      - seq
      - rabbitmq
      - consul
      
  merchant.api:
    image: ${DOCKER_REGISTRY-}merchantapi
    build:
      context: .
      dockerfile: src/Services/Merchant/Merchant.Api/Dockerfile
    depends_on:
      - nosqldata
      - seq
      - rabbitmq
      - consul
        
  search.api:
    image: ${DOCKER_REGISTRY-}searchapi
    build:
      context: .
      dockerfile: src/Services/Search/Search.Api/Dockerfile
    depends_on:
      - seq
      - rabbitmq
      - consul
  
  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: src/Services/Identity/Joker.Identity/Dockerfile
    depends_on:
      - postgres
      - seq
      - rabbitmq      
  
  subscription.api:
    image: ${DOCKER_REGISTRY-}subscriptionapi
    build:
      context: .
      dockerfile: src/Services/Subscription/Subscription.Api/Dockerfile
    depends_on:
      - nosqldata
      - seq
      - rabbitmq
      - consul
    
  aggregator.api:
    image: ${DOCKER_REGISTRY-}aggregatorapi
    build:
      context: .
      dockerfile: src/Aggregators/Aggregator.Api/Dockerfile
    depends_on:
      - identity.api
      - search.api
      - merchant.api
      - management.api
      - subscription.api
      - location.api
      - campaign.api
  
  gateway.web.api:
    image: ${DOCKER_REGISTRY-}gatewaywebapi
    build:
      context: .
      dockerfile: src/Gateways/Gateway.Web.Api/Dockerfile
    depends_on:
      - aggregator.api
        
  joker.webapp:
    image: ${DOCKER_REGISTRY-}jokerwebapp
    build:
      context: .
      dockerfile: src/WebApplications/Joker.WebApp/Dockerfile              
    depends_on:
      - gateway.web.api
