name: Docker Compose CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Docker Compose CI
      run: docker-compose build
    - name: Create Network
      run: docker network create joker-network    
    - name: Integration Tests
      run: docker-compose up --exit-code-from merchant-integration-tests merchant-integration-tests   
